repos:
  - repo: https://github.com/aws-quickstart/qs-cfn-lint-rules
    rev: v1.0.dev0
    hooks:
      - id: qs-cfn-lint
        files: \.\*\.cfn\.(yaml|yml)$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
        args:
          - "--unsafe"
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/Lucas-C/pre-commit-hooks-go
    rev: v1.0.1
    hooks:
      - id: checkmake
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.29.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/Lucas-C/pre-commit-hooks-markup
    rev: 'v1.0.1'  # Use the sha / tag you want to point at
    hooks:
      - id: rst-linter
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.5.0
    hooks:
      - id: check-github-workflows
