AWSTemplateFormatVersion: '2010-09-09'
Description: Creates Account Services

Parameters:

  Prefix:
    Type: "String"
    Description: "Unique Identifier for the whole Project"

  EnvironmentName:
    Type: "String"
    Description: "Name of Environment used deployment"

  ProjectSlug:
    Type: "String"
    Description: "Slug used for the whole Project"

  StackSlug:
    Type: "String"
    Description: "Slug used for current STack"

  UniqueExtension:
    Type: "String"
    Description: "this string can be used to prevent name collisions"
    Default: "0000"

  SeedStackName:
    Type: "String"
    Description: "Name of main-seed stack"

  InfrastructureNetworkStackName:
    Type: "String"
    Description: "Name of Infrastructure Stack (that provides the network)"
    Default: "false"

  RahSecurityGroupIds:
    Type: "CommaDelimitedList"
    Description: "Security Group from Database used in Rah"

  CfnNotificationTopicArn:
    Type: "String"
    Description: "Cloudformation Notification Topic Arn"
    Default: "false"

  FlagAutouseCidashNotificationTopic:
    Type: "String"
    Description: "Automatic usage of Cidash SNS Notification Topic"
    Default: "false"

  FeatureFlagSns2Slack:
    Type: "String"
    Description: "Add SNS Lambda Subscriber to Slack" 
    AllowedValues:
      - "true"
      - "false"
    Default: "false"

  FeatureFlagMysqlLambdaLayer:
    Type: "String"
    Description: "Create pymysql lambda layer stack" 
    AllowedValues:
      - "true"
      - "false"
    Default: "false"

  FeatureFlagPostgresLambdaLayer:
    Type: "String"
    Description: "Create psycopg2 lambda layer stack" 
    AllowedValues:
      - "true"
      - "false"
    Default: "false"

  FeatureFlagCloudTrail:
    Type: "String"
    Description: "Activate CloudTrail Deployment"
    AllowedValues:
      - "true"
      - "false"
    Default: "false"

  FeatureFlagRah:
    Type: "String"
    Description: "Add a Custom CFN Resource that allowes to create additional Users on RDS Databases"
    AllowedValues:
      - "true"
      - "false"
    Default: "false"

  FeatureFlagRandomString:
    Type: "String"
    Description: "Adds a custom Cfn resource that allows to generate random strings"
    Default: "false"
    AllowedValues:
      - "true"
      - "false"

  FeatureFlagCostCredential:
    Type: "String"
    Description: "Creates Credentials for external Monitoring Systems that only allows to get Costs and Billing Information"
    AllowedValues:
      - "true"
      - "false"
    Default: "false"

  FeatureFlagNukeCredential:
    Type: "String"
    Description: "Creates Credentials for account nuking"
    AllowedValues:
      - "true"
      - "false"
    Default: "false"

  MysqlLambdaLayerArn:
    Type: "String"
    Default: "false"
    Description: "ARN of Mysql Lambda Layer. Only needed, if FeatureFlagMysqlLambdaLayer is false but FeatureFlagRah is true"


  PostgresLambdaLayerArn:
    Type: "String"
    Default: "false"
    Description: "ARN of Postgres Lambda Layer. Only needed, if FeatureFlagPostgresLambdaLayer is false but FeatureFlagRah is true"


Conditions:

  HasEnvironment:
    Fn::Not:
      - Fn::Equals:
          - "false"
          - !Ref "EnvironmentName"

  FlagAutouseCidashNotificationTopic:
    Fn::Equals:
      - "true"
      - !Ref "FlagAutouseCidashNotificationTopic"

  FeatureFlagSns2Slack:
    Fn::Equals:
      - "true"
      - !Ref "FeatureFlagSns2Slack"

  FeatureFlagMysqlLambdaLayer:
    Fn::Equals:
      - "true"
      - !Ref "FeatureFlagMysqlLambdaLayer"

  FeatureFlagPostgresLambdaLayer:
    Fn::Equals:
      - "true"
      - !Ref "FeatureFlagPostgresLambdaLayer"

  FeatureFlagCloudTrail:
    Fn::Equals:
      - "true"
      - !Ref "FeatureFlagCloudTrail"

  FeatureFlagRah:
    Fn::Equals:
      - "true"
      - !Ref "FeatureFlagRah"

  FeatureFlagRandomString:
    Fn::Equals:
      - "true"
      - !Ref "FeatureFlagRandomString"


  FeatureFlagCostCredential:
    Fn::Equals:
      - "true"
      - !Ref "FeatureFlagCostCredential"

  FeatureFlagNukeCredential:
    Fn::Equals:
      - "true"
      - !Ref "FeatureFlagNukeCredential"

  MysqlDependencieRah:
    Fn::And:
      - Fn::Equals:
          - !Ref "FeatureFlagMysqlLambdaLayer"
          - "false"
      - Fn::Not:
          - Fn::Equals:
              - !Ref "FeatureFlagRah"
              - "false"

  PostgresDependencieRah:
    Fn::And:
      - Fn::Equals:
          - !Ref "FeatureFlagPostgresLambdaLayer"
          - "false"
      - Fn::Not:
          - Fn::Equals:
              - !Ref "FeatureFlagRah"
              - "false"
Resources:

  CloudTrailStack:
    Type: "AWS::CloudFormation::Stack"
    Condition: "FeatureFlagCloudTrail"
    Properties:
      TemplateURL:
        Fn::Join:
          - "/"
          - - "https:/"
            - Fn::ImportValue:
                !Join [ ":", [ !Ref "SeedStackName", "SeedBucketDomainName" ] ]
            - Fn::If:
                - "HasEnvironment"
                - !Sub "${Prefix}/${EnvironmentName}/${ProjectSlug}/${StackSlug}/${UniqueExtension}"
                - !Sub "${Prefix}/${ProjectSlug}/${StackSlug}/${UniqueExtension}"
            - !Ref "AWS::StackName"
            - "stack/cloudtrail.yml"
      Parameters:
        Prefix: !Ref "Prefix"
        UniqueExtension: !Ref "UniqueExtension"
        ProjectSlug: !Ref "ProjectSlug"
        EnvironmentName: !Ref "EnvironmentName"

  Sns2SlackStack:
    Type: "AWS::CloudFormation::Stack"
    Condition: "FeatureFlagSns2Slack"
    Properties: 
      TemplateURL:
        Fn::Join:
          - "/"
          - - "https:/"
            - Fn::ImportValue:
                !Join [ ":", [ !Ref "SeedStackName", "SeedBucketDomainName" ] ]
            - Fn::If:
                - "HasEnvironment"
                - !Sub "${Prefix}/${EnvironmentName}/${ProjectSlug}/${StackSlug}/${UniqueExtension}"
                - !Sub "${Prefix}/${ProjectSlug}/${StackSlug}/${UniqueExtension}"
            - !Ref "AWS::StackName"
            - "stack/sns2slack.yml"
      Parameters:
        MainStackName: !Ref "AWS::StackName"
        SeedStackName: !Ref "SeedStackName"
        Prefix: !Ref "Prefix"
        UniqueExtension: !Ref "UniqueExtension"
        ProjectSlug: !Ref "ProjectSlug"
        EnvironmentName: !Ref "EnvironmentName"
        CfnNotificationTopicArn: !Ref "CfnNotificationTopicArn"

  PostgresLambdaLayerStack:
    Type: "AWS::CloudFormation::Stack"
    Condition: "FeatureFlagPostgresLambdaLayer"
    Properties:
      TimeoutInMinutes: 5
      TemplateURL:
        Fn::Join:
          - "/"
          - - "https:/"
            - Fn::ImportValue:
                !Join [ ":", [ !Ref "SeedStackName", "SeedBucketDomainName" ] ]
            - Fn::If:
                - "HasEnvironment"
                - !Sub "${Prefix}/${EnvironmentName}/${ProjectSlug}/${StackSlug}/${UniqueExtension}"
                - !Sub "${Prefix}/${ProjectSlug}/${StackSlug}/${UniqueExtension}"
            - !Ref "AWS::StackName"
            - "rah/infrastructure_as_code/cloudformation/lambda_layer.yml"
      Parameters:
        LayerName: "postgresql-layer"
        LayerS3BucketName:
          Fn::ImportValue:
            !Join [ ":", [ !Ref "SeedStackName", "SeedBucketName" ] ]
        LayerS3BucketKey:
          Fn::If:
            - "HasEnvironment"
            - Fn::Join:
                - "/"
                - - !Ref "Prefix"
                  - !Ref "EnvironmentName"
                  - !Ref "ProjectSlug"
                  - !Ref "StackSlug"
                  - !Ref "UniqueExtension"
                  - !Ref "AWS::StackName"
                  - "build/postgres-layer.zip"
            - Fn::Join:
                - "/"
                - - !Ref "Prefix"
                  - !Ref "ProjectSlug"
                  - !Ref "StackSlug"
                  - !Ref "UniqueExtension"
                  - !Ref "AWS::StackName"
                  - "build/postgres-layer.zip"


  MysqlLambdaLayerStack:
    Type: "AWS::CloudFormation::Stack"
    Condition: "FeatureFlagMysqlLambdaLayer"
    Properties:
      TimeoutInMinutes: 5
      TemplateURL:
        Fn::Join:
          - "/"
          - - "https:/"
            - Fn::ImportValue:
                !Join [ ":", [ !Ref "SeedStackName", "SeedBucketDomainName" ] ]
            - Fn::If:
                - "HasEnvironment"
                - !Sub "${Prefix}/${EnvironmentName}/${ProjectSlug}/${StackSlug}/${UniqueExtension}"
                - !Sub "${Prefix}/${ProjectSlug}/${StackSlug}/${UniqueExtension}"
            - !Ref "AWS::StackName"
            - "rah/infrastructure_as_code/cloudformation/lambda_layer.yml"
      Parameters:
        LayerName: "mysql-layer"
        LayerS3BucketName:
          Fn::ImportValue:
            !Join [ ":", [ !Ref "SeedStackName", "SeedBucketName" ] ]
        LayerS3BucketKey:
          Fn::If:
            - "HasEnvironment"
            - Fn::Join:
                - "/"
                - - !Ref "Prefix"
                  - !Ref "EnvironmentName"
                  - !Ref "ProjectSlug"
                  - !Ref "StackSlug"
                  - !Ref "UniqueExtension"
                  - !Ref "AWS::StackName"
                  - "build/mysql-layer.zip"
            - Fn::Join:
                - "/"
                - - !Ref "Prefix"
                  - !Ref "ProjectSlug"
                  - !Ref "StackSlug"
                  - !Ref "UniqueExtension"
                  - !Ref "AWS::StackName"
                  - "build/mysql-layer.zip"

  RahStack:
    Type: "AWS::CloudFormation::Stack"
    Condition: "FeatureFlagRah"
    Properties: 
      TimeoutInMinutes: 5
      TemplateURL:
        Fn::Join:
          - "/"
          - - "https:/"
            - Fn::ImportValue:
                !Join [ ":", [ !Ref "SeedStackName", "SeedBucketDomainName" ] ]
            - Fn::If:
                - "HasEnvironment"
                - !Sub "${Prefix}/${EnvironmentName}/${ProjectSlug}/${StackSlug}/${UniqueExtension}"
                - !Sub "${Prefix}/${ProjectSlug}/${StackSlug}/${UniqueExtension}"
            - !Ref "AWS::StackName"
            - "rah/infrastructure_as_code/cloudformation/cfn_custom_rah.yml"
      Parameters:
        LambdaS3BucketName:
          Fn::ImportValue:
            !Join [ ":", [ !Ref "SeedStackName", "SeedBucketName" ] ]
        LambdaS3BucketKey:
          Fn::If:
            - "HasEnvironment"
            - Fn::Join:
                - "/"
                - - !Ref "Prefix"
                  - !Ref "EnvironmentName"
                  - !Ref "ProjectSlug"
                  - !Ref "StackSlug"
                  - !Ref "UniqueExtension"
                  - !Ref "AWS::StackName"
                  - "build/rah.zip"
            - Fn::Join:
                - "/"
                - - !Ref "Prefix" 
                  - !Ref "ProjectSlug"
                  - !Ref "StackSlug"
                  - !Ref "UniqueExtension"
                  - !Ref "AWS::StackName"
                  - "build/rah.zip"

        MysqlLambdaLayerArn:
          Fn::If:
            - "MysqlDependencieRah"
            - !Ref "MysqlLambdaLayerArn"
            - !GetAtt "MysqlLambdaLayerStack.Outputs.LambdaLayerArn"
        PostgresLambdaLayerArn:
          Fn::If:
            - "PostgresDependencieRah"
            - !Ref "PostgresLambdaLayerArn"
            - !GetAtt "PostgresLambdaLayerStack.Outputs.LambdaLayerArn"
        VpcId:
          Fn::ImportValue:
            !Sub "${InfrastructureNetworkStackName}:VpcId"
        SubnetIds:
          Fn::Join:
            - ","
            - - Fn::ImportValue:
                  !Sub "${InfrastructureNetworkStackName}:PrivateSubnetOne"
              - Fn::ImportValue:
                  !Sub "${InfrastructureNetworkStackName}:PrivateSubnetTwo"
        SecurityGroupIds: !Join [ ",", !Ref "RahSecurityGroupIds" ]

  CostCredentialStack:
    Type: "AWS::CloudFormation::Stack"
    Condition: "FeatureFlagCostCredential"
    Properties: 
      TemplateURL:
        Fn::Join:
          - "/"
          - - "https:/"
            - Fn::ImportValue:
                !Join [ ":", [ !Ref "SeedStackName", "SeedBucketDomainName" ] ]
            - Fn::If:
                - "HasEnvironment"
                - !Sub "${Prefix}/${EnvironmentName}/${ProjectSlug}/${StackSlug}/${UniqueExtension}"
                - !Sub "${Prefix}/${ProjectSlug}/${StackSlug}/${UniqueExtension}"
            - !Ref "AWS::StackName"
            - "stack/cost_credential.yml"
      Parameters:
        MainStackName: !Ref "AWS::StackName"
        SeedStackName: !Ref "SeedStackName"
        UniqueExtension: !Ref "UniqueExtension"
        ProjectSlug: !Ref "ProjectSlug"

  NukeCredentialStack:
    Type: "AWS::CloudFormation::Stack"
    Condition: "FeatureFlagNukeCredential"
    Properties:
      TemplateURL:
        Fn::Join:
          - "/"
          - - "https:/"
            - Fn::ImportValue:
                !Join [ ":", [ !Ref "SeedStackName", "SeedBucketDomainName" ] ]
            - Fn::If:
                - "HasEnvironment"
                - !Sub "${Prefix}/${EnvironmentName}/${ProjectSlug}/${StackSlug}/${UniqueExtension}"
                - !Sub "${Prefix}/${ProjectSlug}/${StackSlug}/${UniqueExtension}"
            - !Ref "AWS::StackName"
            - "stack/nuke_credential.yml"
      Parameters:
        MainStackName: !Ref "AWS::StackName"
        SeedStackName: !Ref "SeedStackName"
        UniqueExtension: !Ref "UniqueExtension"
        ProjectSlug: !Ref "ProjectSlug"

  RandomStringStack:
    Type: "AWS::CloudFormation::Stack"
    Condition: "FeatureFlagRandomString"
    Properties:
      TimeoutInMinutes: 5
      TemplateURL:
        Fn::Join:
          - "/"
          - - "https:/"
            - Fn::ImportValue:
                !Join [ ":", [ !Ref "SeedStackName", "SeedBucketDomainName" ] ]
            - Fn::If:
                - "HasEnvironment"
                - !Sub "${Prefix}/${EnvironmentName}/${ProjectSlug}/${StackSlug}/${UniqueExtension}"
                - !Sub "${Prefix}/${ProjectSlug}/${StackSlug}/${UniqueExtension}"
            - !Ref "AWS::StackName"
            - "stack/random_string.yml"



Outputs:

  RandomStringCustomCfnResourceArn:
    Condition: "FeatureFlagRandomString"
    Value: !GetAtt "RandomStringStack.Outputs.CustomCfnResourceFunctionArn"
    Export:
      Name: !Sub "${AWS::StackName}:RandomStringCustomCfnResourceArn"

  RahCustomCfnResourceArn:
    Condition: "FeatureFlagRah"
    Value: !GetAtt "RahStack.Outputs.CustomCfnResourceFunctionArn"
    Export:
      Name: !Sub "${AWS::StackName}:RahCustomCfnResourceArn"
