AWSTemplateFormatVersion: 2010-09-09
Description: Create Credentials that only allows to Assume roles on other accounts with the Reason to nuke it

Parameters:

  MainStackName:
    Type: "String"
    Description: "Name of Parent Stack"
  
  ProjectSlug:
    Type: "String"
    Description: "Name of Project"

  UniqueExtension:
    Type: "String"
    Description: "String to make the resource naming unique"

  SeedStackName:
    Type: "String"
    Description: "Name of main-seed stack"

Resources:

  NukeCredentialUser:
    Type: "AWS::IAM::User"
    Properties:
      Path: "/bots/any/"
      UserName: "nuke"
      Policies:
        - PolicyName: "bot-nuke"
          PolicyDocument:
            Statement:
              - Effect: "Allow"
                Action:
                  - "sts:AssumeRole"
                Resource: "*"

  NukeCredentialCredentials:
    DependsOn: "NukeCredentialUser"
    Type: "AWS::IAM::AccessKey"
    Properties:
      UserName: "nuke-credential"
    
Outputs:

  NukeCredentialAccessKey:
    Value: !Ref "NukeCredentialCredentials"
    Export:
      Name: !Join [":", [ !Ref "MainStackName", "NukeCredentialAccessKey"] ]

  NukeCredentialSecretAccessKey:
    Value: !GetAtt "NukeCredentialCredentials.SecretAccessKey"
    Export:
      Name: !Join [":", [ !Ref "MainStackName", "NukeCredentialSecretAccessKey"] ]

