name: Default Tests

on:

  push:
    branches:
      - "feature/*"
      - "bug/*"
      - "hotfix/*"
      - "development"

  pull_request:
    branches:
      - "feature/*"
      - "bug/*"
      - "hotfix/*"
      - "development"

jobs:

  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: "Install release dependencies"
      run: make init

    - name: Run a one-line script
      run: make validate