name: Development Workflow

on:
  push:
    branches:
      - "development"
  pull_request:
    branches:
      - "development"

jobs:

  validate:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v1

      - name: "Prepare Checks"
        uses: actions/setup-python@v2
        with:
          node-version: '3.7'

      - name: "Install Dependencies for Checks"
        run: make init

      - name: "Execute Checks"
        run: |
          make validate
          pre-commit

