name: Main Release Workflow

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:

  validate:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v1

      - name: "Prepare Checks"
        uses: actions/setup-python@v2
        with:
          node-version: '3.7'

      - name: "Install Dependencies for Checks"
        run: make init

      - name: "Execute Checks"
        run: |
          make validate
          pre-commit

  bumpversion:
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref != 'refs/heads/staging'
    steps:

      - name: "Prepare Nodejs"
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: "Install Release Dependencie"
        run: npm install semantic-release @semantic-release/release-notes-generator @semantic-release/git @semantic-release/commit-analyzer @semantic-release/changelog

      - name: "Run Semantic Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Publish Code
        run: make push
