name: Staging Workflow

on:
  push:
    branches:
      - "staging"
  pull_request:
    branches:
      - "staging"

jobs:

  validate:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v1

      - name: "Prepare Python"
        uses: actions/setup-python@v2
        with:
          node-version: '3.7'

      - name: "Install release dependencies"
        run: make init

      - name: "Validate Code"
        run: |
          make validate
          pre-commit

  bumpversion:
    runs-on: ubuntu-latest
    needs: validate
    steps:

      - name: "Peparse Nodejs"
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: "Install Release Dependencie"
        run: npm install semantic-release @semantic-release/release-notes-generator @semantic-release/git @semantic-release/commit-analyzer @semantic-release/changelog

      - name: "Create Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
